"""Clamp α on ghost belief rows that lack an audit trail.

A "ghost-α" belief row has `alpha` inflated above the Beta(1,1) prior
with zero supporting evidence in either audit table:

- no rows in ``feedback_history`` (no apply_feedback / hook / deferred /
  sentiment event has run for this belief)
- no rows in ``belief_corroborations`` (no insert_or_corroborate hit
  has re-asserted this belief)

Every current α-mutation path leaves at least one of those trails:

- ``feedback.apply_feedback`` → always inserts into feedback_history
  (`store.insert_feedback_event` at the bottom of the function).
- ``deferred_feedback.sweep_deferred_feedback`` → writes both
  ``UPDATE beliefs SET alpha = alpha + ?`` AND the feedback_history
  row inside the same ``BEGIN IMMEDIATE`` transaction.
- ``store.insert_or_corroborate`` content-hash hit → does NOT bump α
  but DOES record a corroboration row.

So a row with α > 1.0 + a small posterior-fitting tolerance, no
feedback events, and no corroborations is structurally inexplicable
under current production code. Empirically (lab campaign
``retrieval-corpus-bloat`` → ``alpha-gain-third-path``, 2026-05-11),
these rows are 100% pre-migration artifacts preserved verbatim by
``migrate._read_legacy_beliefs``. They cannot be regenerated by any
running code path, so a one-shot clamp is safe and need not be
re-applied.

Reversibility. Every clamp writes a single negative-valence row to
``feedback_history`` with ``source='clamp_ghosts'`` and
``valence = -(prior_alpha - target_alpha)``. To reverse a clamp:

    UPDATE beliefs SET alpha = alpha + (-fh.valence)
    WHERE id IN (SELECT belief_id FROM feedback_history
                 WHERE source = 'clamp_ghosts' AND belief_id = beliefs.id);
    DELETE FROM feedback_history WHERE source = 'clamp_ghosts';

Idempotency. After one successful clamp the rows have feedback_history
entries, so the EXISTS filter excludes them on re-run. A bare
``aelf clamp-ghosts --apply`` is safe to run twice.

The default ``target_alpha = 4.0`` is a posterior-fitting choice: at
α=4, β=1 the posterior mean is 0.8 — still highly retrievable, but
not dominating the BM25 ordering against legitimately-confirmed
beliefs. ``--target`` flag lets the operator pick a different value.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import IO

from aelfrice.store import MemoryStore


CLAMP_SOURCE: str = "clamp_ghosts"
"""``feedback_history.source`` value for clamp-driven audit rows.

Stable across versions: downstream forensic queries
(``SELECT ... WHERE source = 'clamp_ghosts'``) depend on this string."""


DEFAULT_THRESHOLD_ALPHA: float = 4.0
"""α above which a row is considered a ghost candidate. At α=4 the
posterior is ~0.8; below that the row is already in the normal
high-recall band and clamping would be a no-op or worse."""


DEFAULT_TARGET_ALPHA: float = 4.0
"""α value the clamp writes to matching rows. Same number as the
threshold by design — anything matched (α > 4) gets pulled back to
α = 4."""


@dataclass
class ClampResult:
    """Outcome of one clamp_ghost_alphas invocation.

    `matched` and `scanned` are equal under the current implementation
    (no per-row skip logic beyond the SQL filter). The split is kept
    for forward compatibility with future per-row predicates.
    """
    matched: int
    clamped: int
    skipped: int
    dry_run: bool
    threshold_alpha: float
    target_alpha: float
    sample: list[dict] = field(default_factory=list)


def clamp_ghost_alphas(
    store: MemoryStore,
    *,
    threshold_alpha: float = DEFAULT_THRESHOLD_ALPHA,
    target_alpha: float = DEFAULT_TARGET_ALPHA,
    dry_run: bool = True,
    limit: int | None = None,
    stderr: IO[str] | None = None,
) -> ClampResult:
    """Clamp α to ``target_alpha`` on ghost-α belief rows.

    A "ghost-α" row is one where:

    - ``lock_level = 'none'`` (locked beliefs are never clamped — their
      α reflects an explicit user assertion)
    - ``alpha > threshold_alpha``
    - no rows in ``feedback_history`` for this belief
    - no rows in ``belief_corroborations`` for this belief

    Under ``dry_run=True`` (the default) the function returns the
    sample without mutating anything. Pass ``dry_run=False`` to apply.

    Within the apply path, each row's clamp is one ``BEGIN IMMEDIATE``
    transaction containing two writes: the α update on ``beliefs``
    and one negative-valence row on ``feedback_history``. Mirrors the
    transactional shape of ``deferred_feedback.sweep_deferred_feedback``
    so the same atomicity guarantees hold.

    Args:
        store: open MemoryStore.
        threshold_alpha: α floor above which a row is a candidate.
        target_alpha: α value to clamp matching rows down to.
        dry_run: when True, enumerate matches but do not mutate.
        limit: optional cap on rows processed in one call (None = no cap).
        stderr: optional stream for any non-fatal warnings.

    Returns:
        ClampResult with counts and a 10-row sample of matches.

    Raises:
        ValueError: if threshold_alpha < target_alpha (would no-op
            silently); if either value is non-positive.
    """
    if threshold_alpha <= 0 or target_alpha <= 0:
        raise ValueError(
            f"threshold_alpha and target_alpha must be positive; "
            f"got threshold={threshold_alpha} target={target_alpha}"
        )
    if target_alpha > threshold_alpha:
        raise ValueError(
            f"target_alpha ({target_alpha}) must be <= threshold_alpha "
            f"({threshold_alpha}); otherwise no row would be clamped down"
        )

    conn = store._conn  # noqa: SLF001 — same access pattern as deferred_feedback.py:300

    query = (
        "SELECT b.id AS id, b.alpha AS alpha, b.beta AS beta, "
        "substr(b.content, 1, 100) AS preview "
        "FROM beliefs b "
        "WHERE b.lock_level = 'none' "
        "  AND b.alpha > ? "
        "  AND NOT EXISTS ("
        "    SELECT 1 FROM feedback_history fh WHERE fh.belief_id = b.id"
        "  ) "
        "  AND NOT EXISTS ("
        "    SELECT 1 FROM belief_corroborations bc WHERE bc.belief_id = b.id"
        "  ) "
        "ORDER BY b.alpha DESC"
    )
    params: list[object] = [threshold_alpha]
    if limit is not None:
        query += " LIMIT ?"
        params.append(int(limit))

    rows = conn.execute(query, params).fetchall()
    matched = len(rows)
    sample = [
        {
            "id": r["id"],
            "prior_alpha": round(float(r["alpha"]), 3),
            "preview": (r["preview"] or "")[:80],
        }
        for r in rows[:10]
    ]

    if dry_run:
        return ClampResult(
            matched=matched,
            clamped=0,
            skipped=matched,
            dry_run=True,
            threshold_alpha=threshold_alpha,
            target_alpha=target_alpha,
            sample=sample,
        )

    now_iso = datetime.now(timezone.utc).isoformat()
    clamped = 0
    for r in rows:
        try:
            conn.execute("BEGIN IMMEDIATE")
            # Re-check eligibility under the write lock so concurrent
            # --apply runs can't both clamp the same belief and insert
            # duplicate CLAMP_SOURCE audit rows (breaks the one-row
            # reversible-audit invariant).
            current = conn.execute(
                "SELECT b.alpha AS alpha "
                "FROM beliefs b "
                "WHERE b.id = ? "
                "  AND b.lock_level = 'none' "
                "  AND b.alpha > ? "
                "  AND NOT EXISTS ("
                "    SELECT 1 FROM feedback_history fh "
                "    WHERE fh.belief_id = b.id"
                "  ) "
                "  AND NOT EXISTS ("
                "    SELECT 1 FROM belief_corroborations bc "
                "    WHERE bc.belief_id = b.id"
                "  )",
                (r["id"], target_alpha),
            ).fetchone()
            if current is None:
                conn.execute("ROLLBACK")
                continue
            prior = float(current["alpha"])
            delta = -(prior - target_alpha)  # negative valence: reversible audit
            conn.execute(
                "UPDATE beliefs SET alpha = ? WHERE id = ?",
                (target_alpha, r["id"]),
            )
            conn.execute(
                "INSERT INTO feedback_history "
                "(belief_id, valence, source, created_at) "
                "VALUES (?, ?, ?, ?)",
                (r["id"], delta, CLAMP_SOURCE, now_iso),
            )
            conn.execute("COMMIT")
            clamped += 1
        except Exception:
            conn.execute("ROLLBACK")
            raise

    return ClampResult(
        matched=matched,
        clamped=clamped,
        skipped=matched - clamped,
        dry_run=False,
        threshold_alpha=threshold_alpha,
        target_alpha=target_alpha,
        sample=sample,
    )
