"""Origin-tier promotion for v1.2.0+.

Implements the `agent_inferred -> user_validated` promotion path
designed in `docs/promotion_path.md`. The CLI surface is
`aelf validate <belief_id>`; the MCP surface is `aelf:validate`.

Extended in v2.1 (#550) to also accept `origin = ORIGIN_SPECULATIVE`
(phantom beliefs generated by `wonder_ingest`). Two explicit surfaces:

  Surface A — `aelf validate <id>` / `aelf promote <id>` on a phantom.
               Writes `promotion:user_validated` audit row.

  Surface B — `aelf lock <text>` matching a phantom by content_hash or
               Jaccard ≥ 0.9. Writes `promotion:phantom_lock_match`
               audit row (tagged via `SOURCE_PROMOTE_PHANTOM_LOCK_MATCH`).

Provenance change only — no math change. The user clicking validate
does not move alpha/beta. Justification: validation is a UI act,
not a math act. See § 3 of the design memo.

Reversibility lives in `cli._cmd_demote`: when given a
`lock_level=none, origin=user_validated` belief, demote flips origin
back to `agent_inferred` and writes a `promotion:revert_to_agent_inferred`
audit row.

`unlock()` clears a user-lock without touching origin. It is the
pure inverse of `aelf lock`. Writes a `lock:unlock` audit row.
Idempotent — re-unlocking an already-unlocked belief is a no-op.

Audit row shape (every successful promote, devalidate, and unlock):
  - belief_id = subject's id
  - valence   = 0.0  (replay-safe; ignored by feedback math)
  - source    = 'promotion:user_validated' or
                'promotion:phantom_lock_match' or
                'promotion:revert_to_agent_inferred' or
                'lock:unlock'
  - created_at = ISO-8601 UTC, Z-suffixed
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Final

from aelfrice.models import (
    LOCK_NONE,
    LOCK_USER,
    ORIGIN_AGENT_INFERRED,
    ORIGIN_SPECULATIVE,
    ORIGIN_USER_STATED,
    ORIGIN_USER_VALIDATED,
)
from aelfrice.store import MemoryStore

SOURCE_PROMOTE_USER_VALIDATED: Final[str] = "promotion:user_validated"
SOURCE_REVERT_TO_AGENT_INFERRED: Final[str] = (
    "promotion:revert_to_agent_inferred"
)
SOURCE_LOCK_UNLOCK: Final[str] = "lock:unlock"
# Surface B audit label — written when `aelf lock <text>` matches a
# phantom by content_hash exact-match or Jaccard ≥ 0.9.
SOURCE_PROMOTE_PHANTOM_LOCK_MATCH: Final[str] = "promotion:phantom_lock_match"


@dataclass(frozen=True)
class PromotionResult:
    """Outcome of one `promote` call.

    `audit_event_id` is None on the idempotent already-validated path
    (no row is written). `prior_origin` lets the caller see the
    pre-promotion tier without re-reading the store.
    """
    belief_id: str
    prior_origin: str
    new_origin: str
    audit_event_id: int | None
    already_validated: bool


@dataclass(frozen=True)
class UnlockResult:
    """Outcome of one `unlock` call.

    `audit_event_id` is None when `already_unlocked=True`
    (idempotent path — no row is written).
    """
    belief_id: str
    already_unlocked: bool
    audit_event_id: int | None


# --- Surface B: phantom lock-match helper (#550) -------------------------

# Jaccard threshold from docs/v2_phantom_promotion_trigger.md § Surface B.
# Tunable post-benchmark; constant lives here so tests can read it.
PHANTOM_LOCK_JACCARD_THRESHOLD: Final[float] = 0.9

# Minimal stopwords for normalized-text Jaccard. Mirrors the set used by
# relationship_detector to keep the residual subject/predicate tokens.
_PHANTOM_STOPWORDS: Final[frozenset[str]] = frozenset({
    "a", "an", "the", "is", "are", "was", "were", "be", "been", "being",
    "to", "of", "in", "on", "for", "with", "by", "and", "or", "but",
    "if", "then", "than", "as", "at", "from", "this", "that", "these",
    "those", "it", "its", "i", "you", "we", "they", "he", "she", "him",
    "her", "them", "us", "me", "my", "your", "our", "their", "his",
    "hers", "do", "does", "did", "have", "has", "had", "will", "would",
    "should", "could", "can", "into", "about", "over", "under", "out",
    "up", "down", "use", "used", "using", "uses", "any", "some",
})


def _normalize_tokens(text: str) -> frozenset[str]:
    """Lowercase, space-split, stopword-strip — minimal Jaccard normalization.

    Returns a frozenset of residual tokens. Empty input → empty frozenset.
    The result is deterministic and depends only on the input string.
    """
    tokens = {t for t in text.lower().split() if t not in _PHANTOM_STOPWORDS}
    return frozenset(tokens)


def _jaccard(a: frozenset[str], b: frozenset[str]) -> float:
    """Jaccard similarity over two token sets.

    Empty / empty → 1.0 (identical by convention). One empty → 0.0.
    """
    if not a and not b:
        return 1.0
    union = a | b
    if not union:
        return 1.0
    return len(a & b) / len(union)


def find_phantom_lock_matches(
    store: MemoryStore,
    lock_text: str,
    *,
    jaccard_threshold: float = PHANTOM_LOCK_JACCARD_THRESHOLD,
) -> list[str]:
    """Return IDs of active speculative beliefs that match `lock_text`.

    Two-pass scan (fast exact first, then Jaccard):

    Pass 1 — content_hash exact match:
      Compute sha256(lock_text) and check whether any active speculative
      belief carries that content_hash. Phantoms ingested via
      `wonder_ingest` use a constituent-key hash, so this pass catches
      phantoms whose content was originally ingested with the same text
      via a content-hash-compatible path.

    Pass 2 — normalized-text Jaccard ≥ threshold:
      Tokenize both the lock text and each phantom's content (lowercase,
      space-split, stopword-strip). Beliefs not already matched in pass 1
      are included if Jaccard ≥ jaccard_threshold.

    Returns a deduplicated list of belief IDs in scan order (created_at
    ASC). Already-promoted beliefs (origin != ORIGIN_SPECULATIVE) are
    excluded because `list_active_speculative_beliefs` filters them out.

    Pure function on top of the store — no side effects, no audit rows.
    Callers are responsible for calling `promote()` on each returned ID.
    """
    lock_hash = hashlib.sha256(lock_text.encode("utf-8")).hexdigest()
    candidates = store.list_active_speculative_beliefs()

    matched_ids: list[str] = []
    seen: set[str] = set()

    # Pass 1: exact content_hash
    for belief in candidates:
        if belief.content_hash == lock_hash:
            matched_ids.append(belief.id)
            seen.add(belief.id)

    # Pass 2: Jaccard on normalized text
    lock_tokens = _normalize_tokens(lock_text)
    for belief in candidates:
        if belief.id in seen:
            continue
        belief_tokens = _normalize_tokens(belief.content)
        if _jaccard(lock_tokens, belief_tokens) >= jaccard_threshold:
            matched_ids.append(belief.id)
            seen.add(belief.id)

    return matched_ids


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def promote(
    store: MemoryStore,
    belief_id: str,
    *,
    source_label: str = SOURCE_PROMOTE_USER_VALIDATED,
    now: str | None = None,
) -> PromotionResult:
    """Promote `belief_id` to origin=user_validated.

    Provenance flip only — alpha/beta/type/lock_level are unchanged.
    Idempotent: a second call on an already-validated belief is a
    no-op that returns `already_validated=True` and writes no audit
    row.

    Accepted origins (v2.1 #550):
      - agent_inferred, agent_remembered, document_recent, unknown —
        the original promotion targets.
      - speculative — phantom beliefs produced by wonder_ingest.
        Surface A: explicit `aelf validate/promote <id>`.
        Surface B: caller passes SOURCE_PROMOTE_PHANTOM_LOCK_MATCH as
        source_label when promoting via lock-text match.

    Refusal cases (raise ValueError):
      - belief not found
      - belief is locked (lock is a strictly stronger tier; demote
        first via `aelf demote` to drop the lock, then validate)
      - belief is origin=user_stated without lock (data
        inconsistency; same handling as locked)

    The `source_label` argument exists so a UI client can tag its
    promotion distinctly while keeping the `promotion:` prefix —
    pass `"promotion:mcp_validate"` for example.
    """
    # #655: reject foreign belief ids at the mutation surface.
    store.assert_local_ownership(belief_id)
    belief = store.get_belief(belief_id)
    if belief is None:
        raise ValueError(f"belief not found: {belief_id}")
    if belief.lock_level == LOCK_USER:
        raise ValueError(
            f"cannot validate locked belief: {belief_id} "
            "(locks already exceed user_validated; use 'aelf demote' "
            "to drop the lock first)"
        )
    if belief.origin == ORIGIN_USER_STATED:
        raise ValueError(
            f"cannot validate user_stated belief: {belief_id} "
            "(origin already at higher tier; use 'aelf demote' to "
            "drop the lock first)"
        )
    if belief.origin == ORIGIN_USER_VALIDATED:
        return PromotionResult(
            belief_id=belief_id,
            prior_origin=ORIGIN_USER_VALIDATED,
            new_origin=ORIGIN_USER_VALIDATED,
            audit_event_id=None,
            already_validated=True,
        )
    prior = belief.origin
    belief.origin = ORIGIN_USER_VALIDATED
    store.update_belief(belief)
    timestamp = now if now is not None else _utc_now_iso()
    audit_id = store.insert_feedback_event(
        belief_id=belief_id,
        valence=0.0,
        source=source_label,
        created_at=timestamp,
    )
    return PromotionResult(
        belief_id=belief_id,
        prior_origin=prior,
        new_origin=ORIGIN_USER_VALIDATED,
        audit_event_id=audit_id,
        already_validated=False,
    )


def devalidate(
    store: MemoryStore,
    belief_id: str,
    *,
    source_label: str = SOURCE_REVERT_TO_AGENT_INFERRED,
    now: str | None = None,
) -> PromotionResult:
    """Reverse `promote`. Flips origin=user_validated -> agent_inferred.

    Called by `aelf demote` when given a `lock_level=none,
    origin=user_validated` belief. Writes a
    `promotion:revert_to_agent_inferred` audit row so the round-trip
    is visible in the log.

    Returns `already_validated=False` on success. Raises ValueError
    if the belief is missing, locked, or not currently
    `user_validated`.
    """
    # #655: reject foreign belief ids at the mutation surface.
    store.assert_local_ownership(belief_id)
    belief = store.get_belief(belief_id)
    if belief is None:
        raise ValueError(f"belief not found: {belief_id}")
    if belief.lock_level == LOCK_USER:
        raise ValueError(
            f"cannot devalidate locked belief: {belief_id} "
            "(drop the lock first with 'aelf demote')"
        )
    if belief.origin != ORIGIN_USER_VALIDATED:
        raise ValueError(
            f"belief is not user_validated: {belief_id} "
            f"(origin={belief.origin})"
        )
    prior = belief.origin
    belief.origin = ORIGIN_AGENT_INFERRED
    store.update_belief(belief)
    timestamp = now if now is not None else _utc_now_iso()
    audit_id = store.insert_feedback_event(
        belief_id=belief_id,
        valence=0.0,
        source=source_label,
        created_at=timestamp,
    )
    return PromotionResult(
        belief_id=belief_id,
        prior_origin=prior,
        new_origin=ORIGIN_AGENT_INFERRED,
        audit_event_id=audit_id,
        already_validated=False,
    )


def unlock(
    store: MemoryStore,
    belief_id: str,
    *,
    source_label: str = SOURCE_LOCK_UNLOCK,
    now: str | None = None,
) -> UnlockResult:
    """Clear the user-lock on a belief. Pure inverse of `aelf lock`.

    Does not touch origin — the belief's origin tier is unchanged.
    Clears `lock_level`, `locked_at`, and `demotion_pressure`.

    Idempotent: unlocking an already-unlocked belief is a no-op
    (returns `already_unlocked=True`, writes no audit row).

    Refusal cases (raise ValueError):
      - belief not found

    Writes a `lock:unlock` audit row on the active (non-idempotent)
    path so the lock-management history is complete.
    """
    # #655: reject foreign belief ids at the mutation surface.
    store.assert_local_ownership(belief_id)
    belief = store.get_belief(belief_id)
    if belief is None:
        raise ValueError(f"belief not found: {belief_id}")
    if belief.lock_level != LOCK_USER:
        return UnlockResult(
            belief_id=belief_id,
            already_unlocked=True,
            audit_event_id=None,
        )
    belief.lock_level = LOCK_NONE
    belief.locked_at = None
    belief.demotion_pressure = 0
    store.update_belief(belief)
    timestamp = now if now is not None else _utc_now_iso()
    audit_id = store.insert_feedback_event(
        belief_id=belief_id,
        valence=0.0,
        source=source_label,
        created_at=timestamp,
    )
    return UnlockResult(
        belief_id=belief_id,
        already_unlocked=False,
        audit_event_id=audit_id,
    )
