name: typos

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: typos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
